"""
OmniKiosk - Module 5: Local Form-Filling Engine & Step-by-Step Intake
File: local_form_filler.py

Responsible for:
1. Ingesting form schemas (current_form_schema.json) generated by Module 2.
2. Ingesting document OCR payloads and in-memory document buffers from Module 3.
3. Accepting natural conversational input and sign tokens, extracting multi-field slots
   deterministically without external cloud LLMs.
4. Merging conversational data with OCR-derived data with strict provenance and conflict tracking.
5. Providing step-by-step contextual field prompts (TTS for blind mode, visual cards for deaf mode).
6. Automating Playwright DOM injection on the live civic portal (text, number, selects, cascading dropdowns).
7. Performing in-memory file uploads directly from RAM buffers (zero unnecessary disk persistence).
8. Dispatching standard DOM input/change events for frontend validation.
9. Verifying populated DOM state and presenting a clean hand-off for Module 6 governance.
10. Strict citizen privacy: all processing is private and on-device; logs redact sensitive PII.
"""

from __future__ import annotations

import json
import logging
import re
import datetime
from dataclasses import dataclass, field, asdict
from enum import Enum
from pathlib import Path
from typing import Dict, List, Optional, Any, Tuple, Union, Callable

try:
    from playwright.sync_api import sync_playwright, Page, Browser, BrowserContext, Locator, TimeoutError as PlaywrightTimeoutError
    PLAYWRIGHT_AVAILABLE = True
except ImportError:
    PLAYWRIGHT_AVAILABLE = False
    Page = Any  # type: ignore
    Browser = Any  # type: ignore
    BrowserContext = Any  # type: ignore
    Locator = Any  # type: ignore


# ==============================================================================
# PRIVACY & LOGGING CONFIGURATION
# ==============================================================================

logger = logging.getLogger("OmniKiosk.LocalFormFiller")
if not logger.handlers:
    handler = logging.StreamHandler()
    formatter = logging.Formatter("[%(asctime)s] [%(levelname)s] [Module5-FormFiller] %(message)s")
    handler.setFormatter(formatter)
    logger.addHandler(handler)
    logger.setLevel(logging.INFO)


def mask_pii_value(key: str, val: Any) -> str:
    """
    Redacts sensitive citizen PII (Aadhaar, phone, ration card, names) for privacy-safe logging.
    Aadhaar numbers are masked to '********1098'.
    """
    if val is None:
        return "None"
    s = str(val).strip()
    k_lower = key.lower()

    # Aadhaar (12 digits)
    if "aadhaar" in k_lower or "uid" in k_lower or re.fullmatch(r"\d{12}", s):
        digits = re.sub(r"\D", "", s)
        if len(digits) == 12:
            return f"********{digits[-4:]}"
        return "********" + s[-4:] if len(s) >= 4 else "********"

    # Phone / mobile
    if "phone" in k_lower or "mobile" in k_lower:
        digits = re.sub(r"\D", "", s)
        if len(digits) >= 4:
            return f"******{digits[-4:]}"
        return "******"

    # Ration card / Account numbers
    if "ration" in k_lower or "account" in k_lower or "bank" in k_lower:
        if len(s) > 4:
            return f"{'*' * (len(s) - 4)}{s[-4:]}"
        return "****"

    # Full Name
    if "name" in k_lower and not any(x in k_lower for x in ["service", "file", "district"]):
        parts = s.split()
        masked_parts = []
        for p in parts:
            if len(p) > 1:
                masked_parts.append(f"{p[0]}{'*' * (len(p) - 1)}")
            else:
                masked_parts.append(p)
        return " ".join(masked_parts)

    return s


def redact_text_pii(text: str) -> str:
    """Scans and redacts 12-digit Aadhaar UIDs and phone numbers from arbitrary text strings."""
    # 12-digit Aadhaar UID pattern
    text = re.sub(r"\b(\d{4})\s?(\d{4})\s?(\d{4})\b", r"********\3", text)
    # 10-digit mobile pattern
    text = re.sub(r"\b([6-9]\d{5})(\d{4})\b", r"******\2", text)
    return text


# ==============================================================================
# EXCEPTIONS
# ==============================================================================

class FormFillerError(Exception):
    """Base exception for OmniKiosk Module 5."""
    pass


class FormSchemaError(FormFillerError):
    """Raised when form schema is invalid, missing, or malformed."""
    pass


class FieldNotFoundError(FormFillerError):
    """Raised when a specified field selector is not found in the DOM."""
    pass


class FieldValidationError(FormFillerError):
    """Raised when field value fails local syntax/validation constraints."""
    pass


class DropdownOptionNotFoundError(FormFillerError):
    """Raised when a requested option is missing in a select dropdown."""
    pass


class CascadingDropdownError(FormFillerError):
    """Raised when dependent dropdown fails to populate within timeout."""
    pass


class FileInjectionError(FormFillerError):
    """Raised when document file buffer is invalid or attachment fails."""
    pass


class BrowserAutomationError(FormFillerError):
    """Raised when Playwright fails to launch, navigate, or interact with portal."""
    pass


# ==============================================================================
# DATA STRUCTURES
# ==============================================================================

class FieldSource(str, Enum):
    OCR = "ocr"
    CONVERSATION = "conversation"
    SIGN_TOKENS = "sign_tokens"
    DEFAULT = "default"
    USER_OVERRIDE = "user_override"


@dataclass
class FormField:
    """Specification of an individual form input field from Module 2 schema."""
    id: str
    type: str  # text, number, select, file, radio, checkbox, textarea
    label: str = ""
    required: bool = False
    pattern: Optional[str] = None
    min: Optional[str] = None
    max: Optional[str] = None
    options: List[str] = field(default_factory=list)
    accept: Optional[str] = None

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> FormField:
        return cls(
            id=str(data.get("id", "")),
            type=str(data.get("type", "text")).lower(),
            label=str(data.get("label", data.get("id", ""))),
            required=bool(data.get("required", False)),
            pattern=data.get("pattern"),
            min=data.get("min"),
            max=data.get("max"),
            options=[str(opt) for opt in data.get("options", [])],
            accept=data.get("accept"),
        )


@dataclass
class FormSchema:
    """Encapsulates the current form schema handed off by Module 2."""
    service_name: str
    form_url: str
    fields: List[FormField] = field(default_factory=list)
    downloaded_docs: List[str] = field(default_factory=list)

    def get_field(self, field_id: str) -> Optional[FormField]:
        for f in self.fields:
            if f.id == field_id:
                return f
        return None

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> FormSchema:
        if "form_url" not in data:
            raise FormSchemaError("Schema is missing mandatory 'form_url' attribute.")
        fields_raw = data.get("fields", [])
        if not isinstance(fields_raw, list):
            raise FormSchemaError("Schema 'fields' must be a list.")
        fields = [FormField.from_dict(f) for f in fields_raw if isinstance(f, dict)]
        return cls(
            service_name=str(data.get("service_name", "Civic Service Form")),
            form_url=str(data["form_url"]),
            fields=fields,
            downloaded_docs=[str(d) for d in data.get("downloaded_docs", [])],
        )


@dataclass
class FieldValue:
    """Holds a structured value for a field along with provenance."""
    value: Any
    source: FieldSource
    timestamp: str = field(default_factory=lambda: datetime.datetime.now().isoformat())
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ConflictRecord:
    """Records conflicting data points between OCR and conversational input."""
    field_id: str
    existing_value: Any
    existing_source: FieldSource
    incoming_value: Any
    incoming_source: FieldSource
    resolved_value: Any
    resolution_reason: str


@dataclass
class FormFillingResult:
    """Structured report returned after Playwright DOM population and verification."""
    status: str  # POPULATED, PARTIALLY_POPULATED, FAILED
    form_url: str
    fields_populated: List[str] = field(default_factory=list)
    fields_missing: List[str] = field(default_factory=list)
    validation_errors: List[str] = field(default_factory=list)
    dom_values: Dict[str, Any] = field(default_factory=dict)
    conflicts: List[Dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


# ==============================================================================
# ACCESSIBILITY ABSTRACTIONS (SPEECH & VISUAL)
# ==============================================================================

class SpeechEngine:
    """
    Directional Audio & TTS abstraction for Blind / Low-Vision citizens.
    Can be connected to Module 4's TTS pipeline or fallback to safe logging.
    """
    def __init__(self, callback: Optional[Callable[[str], None]] = None):
        self.callback = callback

    def speak(self, text: str) -> None:
        safe_text = redact_text_pii(text)
        logger.info(f"[SpeechEngine / TTS Readback] \"{safe_text}\"")
        if self.callback:
            try:
                self.callback(text)
            except Exception as e:
                logger.warning(f"SpeechEngine callback error: {e}")


class VisualPromptEngine:
    """
    Visual Card & High-Contrast abstraction for Deaf / Non-Verbal citizens.
    Exposes high-visibility prompt cards for the kiosk UI.
    """
    @staticmethod
    def create_card(field: FormField, prompt_text: str) -> Dict[str, Any]:
        return {
            "field_id": field.id,
            "field_label": field.label,
            "field_type": field.type,
            "required": field.required,
            "prompt": prompt_text,
            "options": field.options if field.type == "select" else [],
            "theme": "HIGH_CONTRAST_DARK",
            "border_color": "#FFE600",
            "background": "#000000",
        }


# ==============================================================================
# STEP-BY-STEP FIELD PROMPT ENGINE
# ==============================================================================

class FieldPromptEngine:
    """Generates natural, contextual prompts for each required form field."""

    PROMPT_TEMPLATES: Dict[str, str] = {
        "txtApplicantName": "Please state your full name as it appears on your official ID.",
        "txtAadhaarNo": "Please provide your 12-digit Aadhaar UID number.",
        "ddlDistrict": "Please select your home district.",
        "ddlTaluk": "Please select your taluk.",
        "ddlVillage": "Please select your village office.",
        "txtRationCardNo": "Please provide your ration card number.",
        "txtAnnualIncome": "What is your annual family income in rupees?",
        "ddlPurpose": "What is the purpose of this certificate?",
        "fileAadhaar": "Please place your Aadhaar card on the document scanner tray.",
        "applicantName": "Please state your full name.",
        "aadhaarNo": "Please provide your 12-digit Aadhaar number.",
        "disabilityCategory": "Please specify your disability category.",
        "disabilityPercent": "What is your assessed percentage of disability?",
        "bankAccountNo": "Please provide your bank account number.",
        "ifscCode": "Please provide your bank IFSC code.",
    }

    @classmethod
    def generate_prompt(cls, field: FormField) -> str:
        # Check explicit template
        if field.id in cls.PROMPT_TEMPLATES:
            return cls.PROMPT_TEMPLATES[field.id]

        # Contextual prompt based on type and label
        label = field.label or field.id
        if field.type == "select":
            return f"Please select your {label}."
        elif field.type == "file":
            return f"Please place your {label} document on the scanner."
        elif field.type == "number":
            return f"Please state your {label}."
        else:
            return f"Please provide your {label}."


# ==============================================================================
# LOCAL CONVERSATIONAL MULTI-SLOT EXTRACTOR (EDGE SLM FALLBACK)
# ==============================================================================

class ConversationalSlotExtractor:
    """
    On-device deterministic multi-slot conversational extractor.
    Extracts multiple field values from a single natural narrative statement.
    Works 100% offline with zero external cloud dependencies or API keys.
    """

    KNOWN_DISTRICTS = [
        "Thiruvananthapuram", "Ernakulam", "Kozhikode", "Thrissur", "Kannur",
        "Kollam", "Alappuzha", "Pathanamthitta", "Kottayam", "Idukki",
        "Palakkad", "Malappuram", "Wayanad", "Kasaragod"
    ]

    KNOWN_TALUKS = [
        "Neyyattinkara", "Nedumangad", "Kattakada", "Chirayinkeezhu", "Varkala",
        "Aluva", "Kanayannur", "Kochi", "Kothamangalam", "Kunnathunad", "Muvattupuzha", "North Paravur",
        "Koyilandy", "Thamarassery", "Vadakara", "Chalakudy", "Kodungallur", "Mukundapuram",
        "Taliparamba", "Payyanur", "Iritty", "Thalassery"
    ]

    KNOWN_VILLAGES = [
        "Nemom", "Athiyannoor", "Balaramapuram", "Chenkal", "Kanjiramkulam",
        "Karumkulam", "Kulathoor", "Parassala", "Poovar", "Vizhinjam",
        "Edappally", "Kadavanthra", "Poonithura", "Vyttila", "Kasaba", "Kakkodi", "Olavanna"
    ]

    KNOWN_PURPOSES = [
        ("higher education", "Higher Education"),
        ("college scholarship", "Scholarship"),
        ("scholarship", "Scholarship"),
        ("housing scheme", "Housing Scheme"),
        ("housing", "Housing Scheme"),
        ("general", "General"),
    ]

    def __init__(self, schema: Optional[FormSchema] = None):
        self.schema = schema

    def extract_slots(self, utterance: str) -> Dict[str, Any]:
        """
        Extracts structured form fields from conversational text.
        Supports multi-slot utterances such as:
        "My name is Arun Kumar, my ration card number is 2451098, and my annual family income is 75000 rupees for my college scholarship."
        """
        if not utterance or not utterance.strip():
            return {}

        results: Dict[str, Any] = {}
        text = utterance.strip()
        text_lower = text.lower()

        # 1. Extract Full Name
        # e.g., "My name is Arun Kumar...", "I am Arun Kumar...", "Name: Arun Kumar"
        name_match = re.search(
            r"(?:my\s+name\s+is|i\s+am|applicant(?:\s+name)?(?:\s+is)?)\s+([A-Za-z\s\.]+?)(?:,|\.|\band\b|\bmy\b|\bration\b|\bincome\b|\bfor\b|\bwith\b|$)",
            text,
            re.IGNORECASE
        )
        if name_match:
            candidate_name = name_match.group(1).strip()
            # Clean up common stray words
            candidate_name = re.sub(r"^(mr\.?|mrs\.?|ms\.?|dr\.?)\s+", "", candidate_name, flags=re.IGNORECASE)
            if len(candidate_name.split()) >= 1 and not any(w in candidate_name.lower() for w in ["annual", "income", "ration"]):
                results["txtApplicantName"] = candidate_name
                results["applicantName"] = candidate_name

        # 2. Extract Aadhaar Number (12 digits)
        aadhaar_match = re.search(r"\b(\d{4}\s?\d{4}\s?\d{4})\b", text)
        if aadhaar_match:
            raw_uid = re.sub(r"\s+", "", aadhaar_match.group(1))
            if len(raw_uid) == 12:
                results["txtAadhaarNo"] = raw_uid
                results["aadhaarNo"] = raw_uid

        # 3. Extract Ration Card Number
        ration_match = re.search(
            r"(?:ration\s*card(?:\s*no|\s*number)?(?:\s*is)?)\s*[:=]?\s*([A-Za-z0-9\-_]+)",
            text,
            re.IGNORECASE
        )
        if ration_match:
            results["txtRationCardNo"] = ration_match.group(1).strip()

        # 4. Extract Annual Income
        # Patterns:
        # "annual income is 85000", "family income is 75,000 rupees", "income of 85000"
        income_match = re.search(
            r"(?:annual(?:\s+family)?\s+income(?:\s+is)?|family\s+income(?:\s+is)?|income(?:\s+is|\s+of)?)\s*[:=]?\s*(?:rs\.?|inr|rupees)?\s*([0-9]+(?:,[0-9]+)*)",
            text,
            re.IGNORECASE
        )
        if not income_match:
            # Reverse pattern: "75000 rupees for my college scholarship"
            income_match = re.search(
                r"\b([0-9]{4,8})\s*(?:rupees|rs\.?|inr)\b",
                text,
                re.IGNORECASE
            )

        if income_match:
            clean_income = income_match.group(1).replace(",", "").strip()
            results["txtAnnualIncome"] = clean_income

        # 5. Extract Purpose (matches known options or schema select options)
        purpose_candidates = self.KNOWN_PURPOSES
        if self.schema:
            purpose_field = self.schema.get_field("ddlPurpose")
            if purpose_field and purpose_field.options:
                purpose_candidates = [(opt.lower(), opt) for opt in purpose_field.options]

        for trigger, canonical in purpose_candidates:
            if re.search(rf"\b{re.escape(trigger)}\b", text_lower):
                results["ddlPurpose"] = canonical
                break

        # If not matched yet, check for pattern "purpose is X"
        if "ddlPurpose" not in results:
            p_match = re.search(r"(?:purpose\s+is|for(?:\s+my)?)\s+([A-Za-z\s]+?)(?:,|\.|\band\b|$)", text, re.IGNORECASE)
            if p_match:
                p_text = p_match.group(1).strip().title()
                results["ddlPurpose"] = p_text

        # 6. Extract District / Taluk / Village
        # Districts
        for d in self.KNOWN_DISTRICTS:
            if re.search(rf"\b{re.escape(d)}\b", text, re.IGNORECASE):
                results["ddlDistrict"] = d
                break

        # Taluks
        for t in self.KNOWN_TALUKS:
            if re.search(rf"\b{re.escape(t)}\b", text, re.IGNORECASE):
                results["ddlTaluk"] = t
                break

        # Villages
        for v in self.KNOWN_VILLAGES:
            if re.search(rf"\b{re.escape(v)}\b", text, re.IGNORECASE):
                results["ddlVillage"] = v
                break

        # 7. Additional Civic Fields (Disability, Bank, IFSC)
        ifsc_match = re.search(r"\b([A-Z]{4}0[A-Z0-9]{6})\b", text)
        if ifsc_match:
            results["ifscCode"] = ifsc_match.group(1)

        disability_pct = re.search(r"\b([0-9]{1,3})\s*%\s*(?:disability)?\b", text, re.IGNORECASE)
        if disability_pct:
            results["disabilityPercent"] = disability_pct.group(1)

        logger.info(f"Extracted {len(results)} slot(s) from narrative: {list(results.keys())}")
        return results


# ==============================================================================
# FORM STATE MANAGER & INPUT MERGING
# ==============================================================================

class FormStateManager:
    """
    Maintains local private form state, merges OCR and conversational inputs,
    and tracks provenance and conflict records.
    """
    def __init__(self, schema: FormSchema):
        self.schema = schema
        self.fields_state: Dict[str, FieldValue] = {}
        self.file_buffers: Dict[str, Tuple[str, str, bytes]] = {}  # field_id -> (filename, mimetype, bytes)
        self.conflicts: List[ConflictRecord] = []

    def load_ocr_data(self, ocr_payload: Dict[str, Any]) -> None:
        """
        Consumes structured OCR output from Module 3.
        Maps document fields to schema and stores in-memory document buffer.
        """
        if not ocr_payload:
            return

        extracted = ocr_payload.get("extracted_data", {})
        full_name = extracted.get("full_name")
        aadhaar_no = extracted.get("aadhaar_number")
        dob = extracted.get("dob")

        if full_name:
            # Map to both standard ID conventions
            for fid in ["txtApplicantName", "applicantName"]:
                if self.schema.get_field(fid):
                    self.set_value(fid, full_name, FieldSource.OCR, metadata={"confidence": ocr_payload.get("sharpness_score", 1.0)})

        if aadhaar_no:
            clean_uid = re.sub(r"\s+", "", str(aadhaar_no))
            for fid in ["txtAadhaarNo", "aadhaarNo"]:
                if self.schema.get_field(fid):
                    self.set_value(fid, clean_uid, FieldSource.OCR)

        if dob:
            for fid in ["txtDob", "dob"]:
                if self.schema.get_field(fid):
                    self.set_value(fid, dob, FieldSource.OCR)

        # Handle in-memory document image buffer
        img_buffer = ocr_payload.get("image_buffer")
        if img_buffer:
            if isinstance(img_buffer, (bytes, bytearray)):
                self.attach_file_buffer("fileAadhaar", "aadhaar_card_scanned.png", "image/png", bytes(img_buffer))
            elif isinstance(img_buffer, str):
                # If encoded as utf-8 or mock string
                self.attach_file_buffer("fileAadhaar", "aadhaar_card_scanned.png", "image/png", img_buffer.encode("utf-8"))

        logger.info(
            f"Loaded OCR payload into state. Applicant: {mask_pii_value('name', full_name)}, "
            f"UID: {mask_pii_value('aadhaar', aadhaar_no)}"
        )

    def attach_file_buffer(self, field_id: str, filename: str, mimetype: str, buffer_bytes: bytes) -> None:
        """Attaches an in-memory document file buffer without saving to disk."""
        if not isinstance(buffer_bytes, (bytes, bytearray)):
            raise FileInjectionError(f"Buffer for '{field_id}' must be bytes-like object.")
        if len(buffer_bytes) == 0:
            raise FileInjectionError(f"Buffer for '{field_id}' cannot be empty.")
        self.file_buffers[field_id] = (filename, mimetype, bytes(buffer_bytes))
        self.set_value(field_id, f"[RAM_BUFFER: {filename} ({len(buffer_bytes)} bytes)]", FieldSource.OCR)
        logger.info(f"Attached in-memory file buffer to #{field_id}: {filename} ({len(buffer_bytes)} bytes)")

    def set_value(self, field_id: str, value: Any, source: FieldSource, metadata: Optional[Dict[str, Any]] = None) -> None:
        """Stores or updates a field value with source tracking."""
        self.fields_state[field_id] = FieldValue(
            value=value,
            source=source,
            metadata=metadata or {}
        )

    def merge_inputs(self, conversational_slots: Dict[str, Any], source: FieldSource = FieldSource.CONVERSATION) -> None:
        """
        Merges conversational slot inputs with existing state.
        Precedence Rules:
        - Verified OCR identity (Aadhaar number) has high authority; conflicting spoken
          Aadhaar numbers are flagged in `conflicts` rather than silently discarding.
        - Conversational statements populate unfilled fields or user-declarative fields (income, purpose, district).
        """
        for field_id, new_val in conversational_slots.items():
            if not self.schema.get_field(field_id):
                # Try finding alternative ID in schema (e.g. txtApplicantName vs applicantName)
                alt_field = None
                for f in self.schema.fields:
                    if f.id.lower() == field_id.lower():
                        alt_field = f
                        break
                if not alt_field:
                    continue
                field_id = alt_field.id

            existing = self.fields_state.get(field_id)
            if existing is None:
                self.set_value(field_id, new_val, source)
                logger.info(f"Set #{field_id} from {source.value}: {mask_pii_value(field_id, new_val)}")
            else:
                # Value already exists, check for conflict
                if str(existing.value).strip() != str(new_val).strip():
                    if existing.source == FieldSource.OCR and "aadhaar" in field_id.lower():
                        # OCR Aadhaar has precedence; flag conflict
                        conflict = ConflictRecord(
                            field_id=field_id,
                            existing_value=existing.value,
                            existing_source=existing.source,
                            incoming_value=new_val,
                            incoming_source=source,
                            resolved_value=existing.value,
                            resolution_reason="Preserved verified OCR document identity; flagged conflict for Module 6 audit."
                        )
                        self.conflicts.append(conflict)
                        logger.warning(
                            f"Discrepancy in #{field_id}: OCR had {mask_pii_value(field_id, existing.value)} "
                            f"but conversational input said {mask_pii_value(field_id, new_val)}."
                        )
                    else:
                        # User conversational input overrides default or updates state
                        self.set_value(field_id, new_val, source)
                        logger.info(f"Updated #{field_id} with {source.value}: {mask_pii_value(field_id, new_val)}")

    def get_unfilled_required_fields(self) -> List[FormField]:
        """Returns list of mandatory schema fields that have not yet been populated."""
        unfilled = []
        for f in self.schema.fields:
            if not f.required:
                continue
            if f.type == "file":
                if f.id not in self.file_buffers:
                    unfilled.append(f)
            else:
                if f.id not in self.fields_state or self.fields_state[f.id].value is None:
                    unfilled.append(f)
        return unfilled

    def get_structured_dict(self) -> Dict[str, Any]:
        """Returns clean dictionary of populated field IDs and values."""
        return {fid: fval.value for fid, fval in self.fields_state.items()}


# ==============================================================================
# PLAYWRIGHT AUTONOMOUS DOM INJECTOR
# ==============================================================================

class DOMInjector:
    """
    Autonomous Playwright DOM population engine.
    Injects text, numbers, dropdown options, cascading selections, and in-memory files.
    Dispatches HTML5 input/change events and verifies post-injection state.
    Module 5 NEVER autonomously clicks the final submit button.
    """

    def __init__(self, page: Optional[Page] = None):
        self.page = page

    def set_page(self, page: Page) -> None:
        self.page = page

    def navigate(self, form_url: str, timeout_ms: int = 15000) -> None:
        """Navigates to the civic portal form URL."""
        if not self.page:
            raise BrowserAutomationError("Playwright page instance is not initialized.")
        try:
            logger.info(f"Navigating to civic portal: {form_url}")
            self.page.goto(form_url, timeout=timeout_ms, wait_until="load")
        except Exception as e:
            raise BrowserAutomationError(f"Failed to navigate to '{form_url}': {e}") from e

    def fill_text(self, selector: str, value: str) -> None:
        """Fills a text/textarea field and triggers input and change events."""
        if not self.page:
            raise BrowserAutomationError("Playwright page not set.")
        try:
            loc = self.page.locator(selector)
            loc.wait_for(state="visible", timeout=5000)
            loc.fill(value)
            loc.dispatch_event("input")
            loc.dispatch_event("change")
        except Exception as e:
            raise FieldNotFoundError(f"Failed to fill text into '{selector}': {e}") from e

    def fill_number(self, selector: str, value: Union[int, float, str], min_val: Optional[str] = None, max_val: Optional[str] = None) -> None:
        """Fills a numeric input field with bounds checking."""
        val_str = str(value).replace(",", "").strip()
        try:
            num = float(val_str)
            if min_val is not None and num < float(min_val):
                raise FieldValidationError(f"Value {num} for '{selector}' is below minimum {min_val}.")
            if max_val is not None and num > float(max_val):
                raise FieldValidationError(f"Value {num} for '{selector}' exceeds maximum {max_val}.")
        except ValueError:
            raise FieldValidationError(f"Invalid numeric input '{val_str}' for field '{selector}'.")

        if not self.page:
            raise BrowserAutomationError("Playwright page not set.")

        int_or_float_str = str(int(num)) if num.is_integer() else str(num)
        self.fill_text(selector, int_or_float_str)

    def select_dropdown(self, selector: str, value: str) -> None:
        """Selects a value in a standard <select> dropdown, validating available options."""
        if not self.page:
            raise BrowserAutomationError("Playwright page not set.")
        loc = self.page.locator(selector)
        try:
            loc.wait_for(state="visible", timeout=5000)
        except Exception as e:
            raise FieldNotFoundError(f"Dropdown '{selector}' not found or not visible: {e}") from e

        # Inspect available options
        options_info = self.page.eval_on_selector(
            selector,
            """el => Array.from(el.options).map(o => ({ value: o.value, text: o.text }))"""
        )
        matched_val = None
        for opt in options_info:
            if opt["value"].strip().lower() == value.strip().lower() or opt["text"].strip().lower() == value.strip().lower():
                matched_val = opt["value"]
                break

        if matched_val is None:
            available = [f"{o['text']} ({o['value']})" for o in options_info if o['value']]
            raise DropdownOptionNotFoundError(
                f"Requested option '{value}' not found in dropdown '{selector}'. Available: {available}"
            )

        try:
            loc.select_option(value=matched_val)
            loc.dispatch_event("input")
            loc.dispatch_event("change")
        except Exception as e:
            raise BrowserAutomationError(f"Error selecting option in '{selector}': {e}") from e

    def select_cascading_dropdown(
        self,
        parent_selector: str,
        parent_value: str,
        child_selector: str,
        child_value: str,
        timeout_ms: int = 6000
    ) -> None:
        """
        Handles dependent cascading dropdowns (e.g. District -> Taluk -> Village).
        1. Selects parent option.
        2. Waits until child dropdown options are dynamically populated.
        3. Validates that requested child option exists.
        4. Selects child option.
        """
        if not self.page:
            raise BrowserAutomationError("Playwright page not set.")

        logger.info(f"Cascading dropdown: Setting parent {parent_selector}='{parent_value}' -> {child_selector}='{child_value}'")
        # Step 1: Select parent
        self.select_dropdown(parent_selector, parent_value)

        # Step 2: Wait for child options to be populated (length > 1, ignoring default placeholder)
        child_clean_id = child_selector.replace("#", "")
        js_wait_condition = f"""
            () => {{
                const el = document.getElementById('{child_clean_id}') || document.querySelector('{child_selector}');
                return el && el.options && el.options.length > 1;
            }}
        """
        try:
            self.page.wait_for_function(js_wait_condition, timeout=timeout_ms)
        except Exception as e:
            raise CascadingDropdownError(
                f"Child dropdown '{child_selector}' did not populate options after selecting '{parent_value}' in '{parent_selector}' within {timeout_ms}ms."
            ) from e

        # Step 3 & 4: Select child option
        self.select_dropdown(child_selector, child_value)

    def upload_in_memory_file(
        self,
        selector: str,
        filename: str,
        mimetype: str,
        buffer_bytes: bytes
    ) -> None:
        """
        Injects an in-memory document file buffer into <input type="file"> via Playwright.
        Does NOT write the citizen document to disk.
        """
        if not self.page:
            raise BrowserAutomationError("Playwright page not set.")
        if not buffer_bytes or not isinstance(buffer_bytes, (bytes, bytearray)):
            raise FileInjectionError(f"Invalid in-memory buffer provided for '{selector}'.")

        loc = self.page.locator(selector)
        try:
            loc.wait_for(state="attached", timeout=5000)
            # Playwright set_input_files accepting dict with name, mimeType, buffer
            file_payload = {
                "name": filename,
                "mimeType": mimetype,
                "buffer": bytes(buffer_bytes),
            }
            loc.set_input_files(file_payload)
            loc.dispatch_event("input")
            loc.dispatch_event("change")
            logger.info(f"Successfully injected in-memory file payload into '{selector}': {filename}")
        except Exception as e:
            raise FileInjectionError(f"Playwright failed to attach in-memory file to '{selector}': {e}") from e

    def verify_dom_state(self, schema: FormSchema, state_mgr: FormStateManager) -> FormFillingResult:
        """
        Reads back values from the live page DOM to verify that injection succeeded.
        Ensures `#btnSubmit` was NOT triggered.
        """
        if not self.page:
            raise BrowserAutomationError("Playwright page not set.")

        fields_populated = []
        fields_missing = []
        validation_errors = []
        dom_values = {}

        for field_spec in schema.fields:
            selector = f"#{field_spec.id}"
            try:
                loc = self.page.locator(selector)
                if loc.count() == 0:
                    if field_spec.required:
                        fields_missing.append(field_spec.id)
                        validation_errors.append(f"Required field selector '{selector}' not found in DOM.")
                    continue

                if field_spec.type == "file":
                    # Check file attachment in DOM
                    has_files = self.page.eval_on_selector(
                        selector,
                        "el => el.files && el.files.length > 0"
                    )
                    if has_files:
                        file_name = self.page.eval_on_selector(selector, "el => el.files[0].name")
                        dom_values[field_spec.id] = f"[ATTACHED: {file_name}]"
                        fields_populated.append(field_spec.id)
                    else:
                        if field_spec.required:
                            fields_missing.append(field_spec.id)
                            validation_errors.append(f"File upload '{selector}' has no file attached.")
                elif field_spec.type == "select":
                    # Selected value/text
                    sel_info = self.page.eval_on_selector(
                        selector,
                        """el => ({
                            value: el.value,
                            text: el.options[el.selectedIndex] ? el.options[el.selectedIndex].text : ""
                        })"""
                    )
                    curr_val = sel_info["value"] or sel_info["text"]
                    dom_values[field_spec.id] = curr_val
                    if curr_val and not curr_val.startswith("--"):
                        fields_populated.append(field_spec.id)
                    else:
                        if field_spec.required:
                            fields_missing.append(field_spec.id)
                else:
                    # Text / Number inputs
                    curr_val = loc.input_value()
                    dom_values[field_spec.id] = curr_val
                    if curr_val and curr_val.strip():
                        fields_populated.append(field_spec.id)
                    else:
                        if field_spec.required:
                            fields_missing.append(field_spec.id)

            except Exception as e:
                validation_errors.append(f"Verification error for '{selector}': {e}")
                if field_spec.required:
                    fields_missing.append(field_spec.id)

        status = "POPULATED" if not fields_missing and not validation_errors else "PARTIALLY_POPULATED"
        if len(fields_populated) == 0:
            status = "FAILED"

        return FormFillingResult(
            status=status,
            form_url=schema.form_url,
            fields_populated=fields_populated,
            fields_missing=fields_missing,
            validation_errors=validation_errors,
            dom_values=dom_values,
            conflicts=[asdict(c) for c in state_mgr.conflicts],
        )


# ==============================================================================
# UNIFIED LOCAL FORM FILLER CONTROLLER (PUBLIC API)
# ==============================================================================

class LocalFormFiller:
    """
    Main controller for OmniKiosk Module 5.
    Coordinates schema loading, conversational parsing, state merging,
    accessibility readback, and autonomous Playwright DOM injection.
    """

    def __init__(
        self,
        schema_path: Optional[Union[str, Path]] = None,
        schema_dict: Optional[Dict[str, Any]] = None,
        speech_callback: Optional[Callable[[str], None]] = None,
    ):
        self.schema: Optional[FormSchema] = None
        self.state_mgr: Optional[FormStateManager] = None
        self.slot_extractor: Optional[ConversationalSlotExtractor] = None
        self.dom_injector = DOMInjector()
        self.speech_engine = SpeechEngine(callback=speech_callback)
        self.critic_agent = CriticAgent()
        self.supervisor_agent = SupervisorAgent()
        self.ephemeral_purge = EphemeralPurge()
        self.edge_slm: Optional[EdgeSLM] = None
        self._current_field_index: int = 0

        # Playwright internal handles
        self._pw_instance = None
        self._browser: Optional[Browser] = None
        self._context: Optional[BrowserContext] = None
        self._page: Optional[Page] = None

        if schema_path:
            self.load_schema_from_file(schema_path)
        elif schema_dict:
            self.load_schema_from_dict(schema_dict)

    def load_schema_from_file(self, file_path: Union[str, Path]) -> FormSchema:
        """Loads and parses current_form_schema.json."""
        p = Path(file_path)
        if not p.exists():
            raise FormSchemaError(f"Form schema file '{file_path}' does not exist.")
        try:
            with open(p, "r", encoding="utf-8") as f:
                data = json.load(f)
            return self.load_schema_from_dict(data)
        except json.JSONDecodeError as e:
            raise FormSchemaError(f"Malformed JSON in schema file '{file_path}': {e}") from e

    def load_schema_from_dict(self, data: Dict[str, Any]) -> FormSchema:
        """Loads schema from dictionary payload."""
        self.schema = FormSchema.from_dict(data)
        self.state_mgr = FormStateManager(self.schema)
        self.slot_extractor = ConversationalSlotExtractor(self.schema)
        self.edge_slm = EdgeSLM(self.schema)
        self._current_field_index = 0
        logger.info(f"Loaded schema '{self.schema.service_name}' with {len(self.schema.fields)} fields.")
        return self.schema

    def load_ocr_data(self, ocr_payload: Dict[str, Any]) -> None:
        """Consumes OCR payload and in-memory document buffer from Module 3."""
        if not self.state_mgr:
            raise FormFillerError("Schema must be loaded before ingesting OCR data.")
        self.state_mgr.load_ocr_data(ocr_payload)

    def extract_slots(self, utterance: str) -> Dict[str, Any]:
        """Extracts structured form fields from natural conversational utterance."""
        if not self.slot_extractor:
            self.slot_extractor = ConversationalSlotExtractor(self.schema)
        return self.slot_extractor.extract_slots(utterance)

    def merge_inputs(self, conversational_slots: Dict[str, Any], source: FieldSource = FieldSource.CONVERSATION) -> None:
        """Merges conversational slots into current form state."""
        if not self.state_mgr:
            raise FormFillerError("Schema must be loaded before merging inputs.")
        self.state_mgr.merge_inputs(conversational_slots, source=source)

    def get_next_field(self) -> Optional[FormField]:
        """Returns the next required field that still needs input."""
        if not self.state_mgr or not self.schema:
            return None
        unfilled = self.state_mgr.get_unfilled_required_fields()
        return unfilled[0] if unfilled else None

    def generate_prompt(self, field: Optional[FormField] = None) -> str:
        """Generates a contextual spoken/visual prompt for the active field."""
        target_field = field or self.get_next_field()
        if not target_field:
            return "All required fields have been gathered. Ready for verification."
        prompt = FieldPromptEngine.generate_prompt(target_field)
        self.speech_engine.speak(prompt)
        return prompt

    def get_visual_card(self, field: Optional[FormField] = None) -> Dict[str, Any]:
        """Returns high-contrast visual display card for Deaf mode."""
        target_field = field or self.get_next_field()
        if not target_field:
            return {"status": "COMPLETE", "prompt": "All fields gathered."}
        prompt = FieldPromptEngine.generate_prompt(target_field)
        return VisualPromptEngine.create_card(target_field, prompt)

    def get_state(self) -> Dict[str, Any]:
        """Returns structured dictionary of currently gathered form state."""
        if not self.state_mgr:
            return {}
        return self.state_mgr.get_structured_dict()

    def get_conflicts(self) -> List[Dict[str, Any]]:
        """Returns list of detected data conflicts for Module 6 governance."""
        if not self.state_mgr:
            return []
        return [asdict(c) for c in self.state_mgr.conflicts]

    def populate_form(
        self,
        page: Optional[Page] = None,
        headless: bool = True,
        slow_mo: int = 0,
        portal_base_url: Optional[str] = None
    ) -> FormFillingResult:
        """
        Executes autonomous Playwright DOM injection on the live civic portal.
        Populates text, numbers, dropdowns, cascading selections, and in-memory files.
        Verifies populated state and hands off cleanly without clicking submit.
        """
        if not self.schema or not self.state_mgr:
            raise FormFillerError("Schema and state manager must be initialized before DOM injection.")

        if not PLAYWRIGHT_AVAILABLE:
            raise BrowserAutomationError(
                "Playwright is not installed. Please run: pip install playwright && playwright install chromium"
            )

        close_after = False
        if page is not None:
            self._page = page
            self.dom_injector.set_page(page)
        else:
            self._pw_instance = sync_playwright().start()
            self._browser = self._pw_instance.chromium.launch(headless=headless, slow_mo=slow_mo)
            self._context = self._browser.new_context()
            self._page = self._context.new_page()
            self.dom_injector.set_page(self._page)
            close_after = False  # Keep page alive for Module 6 to inspect

        # Determine target URL
        target_url = self.schema.form_url
        if portal_base_url:
            # Allow overriding localhost:3000 during test fixtures
            if "/forms/" in target_url:
                rel_path = target_url[target_url.find("/forms/"):]
                target_url = f"{portal_base_url.rstrip('/')}{rel_path}"

        # Navigate to target form
        self.dom_injector.navigate(target_url)

        # Plan injection order:
        # Group cascading dropdowns (ddlDistrict -> ddlTaluk -> ddlVillage)
        populated_field_ids = set()
        state = self.state_mgr.fields_state

        # Check for cascading district/taluk/village sequence
        has_cascade = any(f.id in state for f in [self.schema.get_field("ddlDistrict"), self.schema.get_field("ddlTaluk")])
        if "ddlDistrict" in state and "ddlTaluk" in state:
            dist_val = state["ddlDistrict"].value
            taluk_val = state["ddlTaluk"].value
            self.dom_injector.select_cascading_dropdown(
                "#ddlDistrict", str(dist_val),
                "#ddlTaluk", str(taluk_val)
            )
            populated_field_ids.add("ddlDistrict")
            populated_field_ids.add("ddlTaluk")

            if "ddlVillage" in state:
                village_val = state["ddlVillage"].value
                self.dom_injector.select_cascading_dropdown(
                    "#ddlTaluk", str(taluk_val),
                    "#ddlVillage", str(village_val)
                )
                populated_field_ids.add("ddlVillage")

        # Populate remaining fields from state
        for field_id, field_val in state.items():
            if field_id in populated_field_ids:
                continue

            field_spec = self.schema.get_field(field_id)
            if not field_spec:
                continue

            selector = f"#{field_id}"
            val = field_val.value

            if field_spec.type == "text" or field_spec.type == "textarea":
                self.dom_injector.fill_text(selector, str(val))
                populated_field_ids.add(field_id)

            elif field_spec.type == "number":
                self.dom_injector.fill_number(selector, val, min_val=field_spec.min, max_val=field_spec.max)
                populated_field_ids.add(field_id)

            elif field_spec.type == "select":
                self.dom_injector.select_dropdown(selector, str(val))
                populated_field_ids.add(field_id)

        # Handle in-memory file uploads
        for file_field_id, (fname, mtype, fbuf) in self.state_mgr.file_buffers.items():
            selector = f"#{file_field_id}"
            self.dom_injector.upload_in_memory_file(selector, fname, mtype, fbuf)
            populated_field_ids.add(file_field_id)

        # Post-injection verification
        verification_result = self.dom_injector.verify_dom_state(self.schema, self.state_mgr)
        logger.info(
            f"DOM Injection complete. Status: {verification_result.status}, "
            f"Populated: {len(verification_result.fields_populated)}, "
            f"Missing: {len(verification_result.fields_missing)}"
        )

        return verification_result

    def close(self) -> None:
        """Closes internal browser context and releases Playwright resources."""
        try:
            if self._context:
                self._context.close()
            if self._browser:
                self._browser.close()
            if self._pw_instance:
                self._pw_instance.stop()
        except Exception as e:
            logger.warning(f"Error during browser teardown: {e}")
        finally:
            self._context = None
            self._browser = None
            self._page = None
            self._pw_instance = None


# ==============================================================================
# TIER 1: ON-DEVICE EDGE SLM (CONVERSATIONAL EXTRACTOR EXTENSION)
# ==============================================================================

class EdgeSLM(ConversationalSlotExtractor):
    """
    Tier 1 On-Device Edge SLM abstraction.
    Runs local deterministic regex/entity slot extraction by default.
    Provides offline parsing of natural narratives and sign tokens with zero cloud calls.
    """
    def __init__(self, schema: Optional[FormSchema] = None, model_path: Optional[str] = None):
        super().__init__(schema)
        self.model_path = model_path
        self.is_quantized = bool(model_path)


# ==============================================================================
# CRITIC AGENT (PRE-SUBMISSION VERIFICATION GUARDRAIL)
# ==============================================================================

class CriticAgent:
    """
    Critic Verification Guardrail for pre-submission form validation.
    Performs regex audit (12-digit Aadhaar, positive income, mandatory fields,
    discrepancy detection between OCR document and conversational spoken data).
    """

    @staticmethod
    def validate_aadhaar_checksum(aadhaar: str) -> bool:
        """Validates 12-digit Aadhaar pattern."""
        clean = re.sub(r"\D", "", str(aadhaar))
        return bool(re.fullmatch(r"[0-9]{12}", clean))

    @staticmethod
    def calculate_string_similarity(s1: str, s2: str) -> float:
        """Computes simple Levenshtein-like character overlap ratio for name discrepancy checks."""
        w1 = set(s1.lower().split())
        w2 = set(s2.lower().split())
        if not w1 or not w2:
            return 0.0
        overlap = len(w1.intersection(w2))
        return overlap / max(len(w1), len(w2))

    def audit_state(
        self,
        schema: FormSchema,
        state_mgr: FormStateManager
    ) -> Tuple[bool, List[str]]:
        """
        Runs comprehensive pre-submission audit against current state.
        Returns (is_valid, list_of_errors_or_warnings).
        """
        errors: List[str] = []
        state = state_mgr.fields_state

        for field_spec in schema.fields:
            fid = field_spec.id
            if field_spec.required:
                if field_spec.type == "file":
                    if fid not in state_mgr.file_buffers:
                        errors.append(f"Missing mandatory file buffer for #{fid}.")
                else:
                    if fid not in state or state[fid].value is None or str(state[fid].value).strip() == "":
                        errors.append(f"Missing mandatory field #{fid} ({field_spec.label}).")

        # 1. Aadhaar UID Syntax check
        for uid_key in ["txtAadhaarNo", "aadhaarNo"]:
            if uid_key in state and state[uid_key].value:
                val = str(state[uid_key].value)
                if not self.validate_aadhaar_checksum(val):
                    errors.append(f"Invalid Aadhaar syntax for #{uid_key}: expected exactly 12 digits.")

        # 2. Annual Income positive numeric check
        if "txtAnnualIncome" in state and state["txtAnnualIncome"].value is not None:
            try:
                income_val = float(str(state["txtAnnualIncome"].value).replace(",", ""))
                if income_val <= 0:
                    errors.append(f"Annual income must be a positive number greater than 0, got {income_val}.")
            except ValueError:
                errors.append("Annual income is not a valid number.")

        # 3. Mandatory Cascading dropdown checks
        for ddl_key in ["ddlDistrict", "ddlTaluk", "ddlVillage"]:
            if ddl_key in state:
                val = str(state[ddl_key].value)
                if not val or val.startswith("--"):
                    errors.append(f"Dropdown #{ddl_key} is on unselected/placeholder value.")

        # 4. Discrepancy checks (Spoken name vs OCR document name)
        for name_key in ["txtApplicantName", "applicantName"]:
            if name_key in state:
                fval = state[name_key]
                if fval.source == FieldSource.CONVERSATION and state_mgr.conflicts:
                    for c in state_mgr.conflicts:
                        if c.field_id == name_key:
                            sim = self.calculate_string_similarity(str(c.existing_value), str(c.incoming_value))
                            if sim < 0.5:
                                errors.append(
                                    f"Discrepancy detected in applicant name: OCR document has "
                                    f"'{mask_pii_value('name', c.existing_value)}' but conversational input stated "
                                    f"'{mask_pii_value('name', c.incoming_value)}'."
                                )

        is_valid = len(errors) == 0
        return is_valid, errors


# ==============================================================================
# SUPERVISOR AGENT (HUMAN-IN-THE-LOOP INTERLOCK GATE)
# ==============================================================================

class SupervisorAgent:
    """
    Human-in-the-Loop circuit breaker for final submission verification.
    Architecturally blocks automated submission without explicit confirmation.
    Generates multimodal pre-submit summary (Audio readback or High-Contrast visual card).
    """

    def __init__(self):
        self._is_locked: bool = True
        self._execution_token: Optional[str] = None

    def generate_summary(self, state_dict: Dict[str, Any]) -> Tuple[str, Dict[str, Any]]:
        """
        Generates:
        1. Directional TTS spoken summary string for blind/low-vision citizens.
        2. High-contrast visual review card for deaf/sign language citizens.
        """
        name = state_dict.get("txtApplicantName") or state_dict.get("applicantName") or "Applicant"
        aadhaar = state_dict.get("txtAadhaarNo") or state_dict.get("aadhaarNo") or ""
        masked_aadhaar = f"ending in {aadhaar[-4:]}" if len(aadhaar) >= 4 else "provided"
        income = state_dict.get("txtAnnualIncome") or "stated"
        district = state_dict.get("ddlDistrict") or "selected district"
        purpose = state_dict.get("ddlPurpose") or "Income Certificate"

        spoken_summary = (
            f"Please verify your application details: Name {name}, Aadhaar {masked_aadhaar}, "
            f"Annual income {income} rupees for {purpose}, located in {district}. "
            f"Please say 'Submit' or give a Thumbs-Up gesture to confirm."
        )

        visual_card = {
            "title": "Review Application Details",
            "applicant_name": name,
            "aadhaar_masked": mask_pii_value("aadhaar", aadhaar),
            "annual_income": f"Rs. {income}",
            "district": district,
            "purpose": purpose,
            "action_prompt": "Show Thumbs-Up gesture or press Submit to confirm.",
            "theme": "HIGH_CONTRAST_DARK",
            "border_color": "#FFE600",
            "background": "#000000",
        }

        return spoken_summary, visual_card

    def process_confirmation(self, signal: str) -> bool:
        """
        Processes human confirmation signal.
        Accepts: 'Submit', 'Confirm', 'yes', 'THUMBS_UP'.
        Rejects: 'Cancel', 'Open_Palm', 'no'.
        """
        sig = signal.strip().lower()
        valid_confirmations = ["submit", "confirm", "yes", "thumbs_up", "thumbs-up", "confirmed"]

        if any(c in sig for c in valid_confirmations):
            self._is_locked = False
            self._execution_token = f"EXEC_TOKEN_{datetime.datetime.now().strftime('%Y%m%d%H%M%S%f')}"
            logger.info(f"Supervisor Agent: Human confirmation verified. Token issued: {self._execution_token}")
            return True
        else:
            self._is_locked = True
            self._execution_token = None
            logger.warning(f"Supervisor Agent: Submission rejected or cancelled via signal '{signal}'.")
            return False

    def is_unlocked(self) -> bool:
        return not self._is_locked and self._execution_token is not None

    def get_token(self) -> Optional[str]:
        return self._execution_token


# ==============================================================================
# EPHEMERAL PURGE (SECURE VOLATILE MEMORY ZEROIZATION)
# ==============================================================================

class EphemeralPurge:
    """
    Cryptographic volatile memory zeroization and ephemeral session purge.
    Overwrites sensitive RAM buffers with zeros and terminates Playwright browser sessions.
    """

    @staticmethod
    def zeroize_bytes(b: Union[bytes, bytearray]) -> bytearray:
        """Zeroizes a mutable bytearray in RAM."""
        ba = bytearray(b)
        for i in range(len(ba)):
            ba[i] = 0
        return ba

    @classmethod
    def purge_state_manager(cls, state_mgr: FormStateManager) -> None:
        """Overwrites and purges all document buffers, fields, and conflicts from RAM."""
        # Overwrite all file buffers with zeros
        for fid, (fname, mtype, fbuf) in list(state_mgr.file_buffers.items()):
            zeroed = cls.zeroize_bytes(fbuf)
            del fbuf
            state_mgr.file_buffers[fid] = (fname, mtype, bytes(zeroed))

        state_mgr.file_buffers.clear()
        state_mgr.fields_state.clear()
        state_mgr.conflicts.clear()
        logger.info("EphemeralPurge: Volatile RAM buffers and state dictionary successfully zeroized.")

    @classmethod
    def purge_filler(cls, filler: LocalFormFiller) -> None:
        """Complete purge of filler state and browser context."""
        if filler.state_mgr:
            cls.purge_state_manager(filler.state_mgr)
        filler.close()
        logger.info("EphemeralPurge: LocalFormFiller session terminated and cleaned.")
